backend:
  name: github
  repo: gabrielcodeproject/pool
  branch: main
  client_id: Ov23likdjdw5uy0twWt9
  base_url: https://pool-cms-oauth.onrender.com
  auth_endpoint: auth
  local_backend: true
##  site_domain: zingy-gnome-ade060.netlify.app

media_folder: "public/images/uploads"
public_folder: "/pool/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Promo 1 Image"
        name: "promo_1_image"
        widget: "image"
      - label: "Promo 1 Text"
        name: "promo_1_text"
        widget: "string"
      - label: "Promo 2 Image"
        name: "promo_2_image"
        widget: "image"
      - label: "Promo 2 Text"
        name: "promo_2_text"
        widget: "string"
      - label: "Promo 3 Image"
        name: "promo_3_image"
        widget: "image"
      - label: "Promo 3 Text"
        name: "promo_3_text"
        widget: "string"
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            required: true
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Price"
            name: "price"
            widget: "number"
            required: true
            min: 0
            hint: "Price in CAD"
      - label: "Body"
        name: "body"
        widget: "markdown"
